name: woozy_search
description: A super simple and lightweight client-side fuzzy-search library based on Levenshtein distance.
version: 2.0.0
homepage: https://github.com/IvoriApp/woozy-search

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  # https://pub.dev/packages/collection
  collection: '>=1.14.12 <2.0.0'
  # https://pub.dev/packages/meta
  meta: '>=1.1.8 <2.0.0'

dev_dependencies:
  uuid: ^2.2.0
  pedantic: ^1.9.0
  test: ^1.14.4
