name: woozy_search
description: A super simple and lightweight client-side fuzzy-search library based on Levenshtein distance.
version: 2.0.3
homepage: https://github.com/IvoriApp/woozy-search

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  # https://pub.dev/packages/collection
  collection: '>=1.15.0 <2.0.0'

dev_dependencies:
  uuid: ^3.0.3
  pedantic: ^1.11.0
  test: ^1.16.8
